"""Deterministic spec -> plan-file-text rendering. No LLM involved here --
this is the one place free-form text becomes Python source, and it is plain
string templating over an already-validated kwargs dict (see plan_spec.py).

Each rendered file is a thin wrapper: a new, small, GUI-documented function
that calls straight through to the real, tested plan in ``instrument/plans/``
(``mpe_step_scan`` / ``mpe_count``) with the chosen values as its own
defaults -- so a human can still tweak them via the GUI's plan-runner form
before running, without opening the file.
"""
from __future__ import annotations

import re

from .device_catalog import DeviceCatalog
from .plan_context import COUNT, STEP_SCAN, Template

HEADER = '''"""GENERATED BY AUTOPILOT -- REVIEW BEFORE USE.

{summary}

This file is a DRAFT, written to AutoPILOT/generated_plans/ for review. Move
it into instrument/plans/ before running -- its relative imports assume that
location. Delete this header comment once you've reviewed the plan.
"""
'''

_CALL_BODY = {
    STEP_SCAN: (
        "    yield from mpe_step_scan(\n"
        "        motor, start, stop,\n"
        "        nsteps=nsteps, det=det, exposure_time=exposure_time, scalers=scalers,\n"
        "    )\n"
    ),
    COUNT: (
        "    yield from mpe_count(\n"
        "        scalers=scalers, nframes=nframes, exposure_time=exposure_time,\n"
        "    )\n"
    ),
}


def _slug(text: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", text).strip("_").lower()


def _typespec(spec) -> str:
    if spec.dtype in ("device", "device_list", "block", "block_list"):
        base = f"{spec.dtype}{{{spec.category}}}"
    elif spec.dtype == "choice":
        base = f"choice{{{', '.join(spec.choices or [])}}}"
    else:
        base = spec.dtype
    return f"{base} [{spec.units}]" if spec.units else base


def _default_code(spec, value) -> str:
    if spec.dtype in ("device", "block"):
        # Both are real Python identifiers (an ophyd object or a
        # building-block function) bound via imports -- never a quoted string.
        return "None" if value is None else str(value)
    if spec.dtype in ("device_list", "block_list"):
        # Lists of real Python identifiers -- emitted unquoted, same reason.
        return "[" + ", ".join(str(v) for v in (value or [])) + "]"
    return repr(value)


def _signature_default_code(spec, value) -> str:
    """Like `_default_code`, except a `device_list` param defaults to `None`
    in a *function signature* -- a literal list there would be Python's
    classic mutable-default-argument footgun, evaluated once at def time and
    shared across every call. `render()` pairs this with a body-line guard
    that rebuilds the real default list fresh on each call instead. Only
    `render()`'s signature line needs this; `render_command()` builds a call
    expression, not a signature, so `_default_code` is safe there as-is.
    """
    if spec.dtype in ("device_list", "block_list"):
        return "None"
    return _default_code(spec, value)


def _device_names_used(template: Template, clean: dict) -> list[str]:
    names: list[str] = []
    for spec in template.param_specs:
        if spec.dtype == "device" and clean.get(spec.name):
            names.append(clean[spec.name])
        elif spec.dtype == "device_list":
            names.extend(clean.get(spec.name) or [])
    return sorted(set(names))


def _axes_tokens(template: Template, clean: dict) -> list[str]:
    """Flatten ``clean["__axes__"]`` (see plan_spec.py's `_validate_axes_item`)
    into positional ``RE(...)`` tokens, mirroring
    B_PILOT/skeleton_widgets.py's ``_MotorRow.tokens()``/``MotorRowsWidget``
    row-by-row concatenation: one motor token followed by that shape's
    position tokens, repeated per row, with no separator between rows.
    """
    shape, _relative = template.skeleton
    tokens: list[str] = []
    for row in clean.get("__axes__") or []:
        tokens.append(row["motor"])
        if shape in ("list", "list_grid"):
            tokens.append("[" + ", ".join(repr(p) for p in row["positions"]) + "]")
        else:
            tokens.append(repr(row["start"]))
            tokens.append(repr(row["stop"]))
            if shape == "step_grid":
                tokens.append(repr(row["nsteps"]))
    return tokens


def render_command(template: Template, clean: dict) -> str:
    """Return an ``RE(<real_plan>(...))`` string for a GUI-drivable template
    (``template.gui_plan_name`` set) -- fed straight into B-PILOT's own
    ``PlanRunnerPanel.load_from_command()`` rather than a generated file.
    Reuses ``_default_code`` so device/device_list/block values come out as
    bare identifiers (real ophyd objects / functions), exactly what that
    AST-based restore expects.

    When ``template.skeleton`` is set (the six scan_skeletons.py plans), the
    motor(s)/position(s) are a bare positional ``*args`` prefix rather than
    ParamSpec-backed keywords -- see ``_apply_skeleton_args()`` in
    B_PILOT/plan_runner.py, which expects to find them first and chunk them by
    row width.
    """
    args = [f"{spec.name}={_default_code(spec, clean.get(spec.name))}" for spec in template.param_specs]
    if template.skeleton:
        args = _axes_tokens(template, clean) + args
    return f"RE({template.gui_plan_name}({', '.join(args)}))"


def render(template: Template, clean: dict, catalog: DeviceCatalog, summary: str) -> tuple[str, str]:
    """Return (filename, file_text) for the validated `clean` kwargs."""
    device_names = _device_names_used(template, clean)
    device_imports = [catalog.import_line_for(name) for name in device_names]

    sig_lines = []
    doc_lines = []
    guard_lines = []
    for spec in template.param_specs:
        sig_lines.append(f"    {spec.name}={_signature_default_code(spec, clean.get(spec.name))},")
        doc_lines.append(f"    {spec.name} : {_typespec(spec)}")
        doc_lines.append(f"        {spec.short} :: {spec.long}")
        doc_lines.append("")
        if spec.dtype in ("device_list", "block_list"):
            default_literal = _default_code(spec, clean.get(spec.name))
            guard_lines.append(f"    {spec.name} = list({spec.name}) if {spec.name} else {default_literal}")

    slug = clean.get("motor") or (clean.get("scalers") or [None])[0] or template.wrapper_name_hint
    func_name = f"autopilot_{template.wrapper_name_hint}_{_slug(str(slug))}"

    body = [
        HEADER.format(summary=summary),
        "",
        f"from .{template.module} import {template.function}",
        *device_imports,
        "",
        "",
        f"def {func_name}(",
        *sig_lines,
        "):",
        '    """',
        f"    {summary}",
        "",
        "    Parameters",
        "    ----------",
        *doc_lines,
        '    """',
        *guard_lines,
        _CALL_BODY[template.key].rstrip("\n"),
        "",
    ]
    return f"{func_name}.py", "\n".join(body) + "\n"
