"""Deterministic spec -> plan-file-text rendering. No LLM involved here --
this is the one place free-form text becomes Python source, and it is plain
string templating over an already-validated kwargs dict (see plan_spec.py).

Each rendered file is a thin wrapper: a new, small, GUI-documented function
that calls straight through to the real, tested plan in ``instrument/plans/``
(``mpe_step_scan`` / ``mpe_count``) with the chosen values as its own
defaults -- so a human can still tweak them via the GUI's plan-runner form
before running, without opening the file.
"""
from __future__ import annotations

import re

from .device_catalog import DeviceCatalog
from .plan_context import COUNT, STEP_SCAN, Template

HEADER = '''"""GENERATED BY AUTOPILOT -- REVIEW BEFORE USE.

{summary}

This file is a DRAFT, written to AutoPILOT/generated_plans/ for review. Move
it into instrument/plans/ before running -- its relative imports assume that
location. Delete this header comment once you've reviewed the plan.
"""
'''

_CALL_BODY = {
    STEP_SCAN: (
        "    yield from mpe_step_scan(\n"
        "        motor, start, stop,\n"
        "        nsteps=nsteps, det=det, exposure_time=exposure_time, scalers=scalers,\n"
        "    )\n"
    ),
    COUNT: (
        "    yield from mpe_count(\n"
        "        scalers=scalers, nframes=nframes, exposure_time=exposure_time,\n"
        "    )\n"
    ),
}


def _slug(text: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", text).strip("_").lower()


def _typespec(spec) -> str:
    if spec.dtype in ("device", "device_list"):
        base = f"{spec.dtype}{{{spec.category}}}"
    elif spec.dtype == "choice":
        base = f"choice{{{', '.join(spec.choices or [])}}}"
    else:
        base = spec.dtype
    return f"{base} [{spec.units}]" if spec.units else base


def _default_code(spec, value) -> str:
    if spec.dtype == "device":
        return "None" if value is None else str(value)
    if spec.dtype == "device_list":
        return "[" + ", ".join(str(v) for v in (value or [])) + "]"
    return repr(value)


def _device_names_used(template: Template, clean: dict) -> list[str]:
    names: list[str] = []
    for spec in template.param_specs:
        if spec.dtype == "device" and clean.get(spec.name):
            names.append(clean[spec.name])
        elif spec.dtype == "device_list":
            names.extend(clean.get(spec.name) or [])
    return sorted(set(names))


def render_command(template: Template, clean: dict) -> str:
    """Return an ``RE(<real_plan>(...))`` string for a GUI-drivable template
    (``template.gui_plan_name`` set) -- fed straight into B-PILOT's own
    ``PlanRunnerPanel.load_from_command()`` rather than a generated file.
    Reuses ``_default_code`` so device/device_list values come out as bare
    identifiers (real ophyd objects), exactly what that AST-based restore
    expects.
    """
    args = [f"{spec.name}={_default_code(spec, clean.get(spec.name))}" for spec in template.param_specs]
    return f"RE({template.gui_plan_name}({', '.join(args)}))"


def render(template: Template, clean: dict, catalog: DeviceCatalog, summary: str) -> tuple[str, str]:
    """Return (filename, file_text) for the validated `clean` kwargs."""
    device_names = _device_names_used(template, clean)
    device_imports = [catalog.import_line_for(name) for name in device_names]

    sig_lines = []
    doc_lines = []
    for spec in template.param_specs:
        sig_lines.append(f"    {spec.name}={_default_code(spec, clean.get(spec.name))},")
        doc_lines.append(f"    {spec.name} : {_typespec(spec)}")
        doc_lines.append(f"        {spec.short} :: {spec.long}")
        doc_lines.append("")

    slug = clean.get("motor") or (clean.get("scalers") or [None])[0] or template.wrapper_name_hint
    func_name = f"autopilot_{template.wrapper_name_hint}_{_slug(str(slug))}"

    body = [
        HEADER.format(summary=summary),
        "",
        f"from .{template.module} import {template.function}",
        *device_imports,
        "",
        "",
        f"def {func_name}(",
        *sig_lines,
        "):",
        '    """',
        f"    {summary}",
        "",
        "    Parameters",
        "    ----------",
        *doc_lines,
        '    """',
        _CALL_BODY[template.key].rstrip("\n"),
        "",
    ]
    return f"{func_name}.py", "\n".join(body) + "\n"
